[project]
name = 'StacksSubscriptionManager'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.subscription]
path = 'contracts/subscription.clar'
clarity_version = 2
epoch = 2.5

[contracts.subscription-enhanced]
path = 'contracts/subscription-enhanced.clar'
clarity_version = 2
epoch = 2.5

[contracts.subscription-transfer]
path = 'contracts/subscription-transfer.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
